name: Lint and Test
on:
  push:
    paths:
      - src/**
      - resources/**
      - deps.edn
jobs:
  lint-and-test:
    runs-on: ubuntu-18.04
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      -
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: latest
          clj-kondo: latest
      -
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      -
        run: clj-kondo --lint src/
